project:
  type: website
  title: "Introduction to Python and Conda"
  output-dir: "_site"
  
website:
  title: "Introduction to Python and Conda"
  description: "This course provides a comprehensive introduction to Python programming and the Conda package management system."
  repo-url: "https://github.com/jfimbett/PythonConda"
  
  navbar:
    title: "Intro to Python & Conda"
    left:
      - text: "Home"
        href: index.html
      - text: "Slides"
        href: src/python-conda-course.qmd
    right:
      - icon: github
        href: "https://github.com/jfimbett/PythonConda"

format:
  html:
    theme: 
      - cosmo
      - src/assets/styles.css # where custom styles are located
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 3
    code-fold: false
    code-tools: true
    citations-hover: true
    footnotes-hover: true
    
  revealjs:
    theme: white
    css: src/assets/styles.css
    slide-number: true
    chalkboard: true
    preview-links: auto
    transition: slide
    background-transition: fade
    hash-type: number
    controls: true
    progress: true
    center: false
    incremental: true
    
execute:
  freeze: auto
  cache: true

editor: visual
